[workspace]
authors = ["Benjamin-Yu-Sheng-Chang <benji.chang@mail.utoronto.ca>"]
channels = ["conda-forge"]
name = "MATD92"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
plotly = ">=6.5.2,<7"
pip = ">=25.3,<26"
ipykernel = ">=7.1.0,<8"
